import { Inter } from "next/font/google";
import "./globals.css";
import HeaderContainer from "./components/HeaderContainer";
import ClientProvider from "./components/ClientProvider";
import LanguageProvider from "./components/LanguageProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body className={`${inter.className}`}>
        <LanguageProvider>
          <ClientProvider>
            <HeaderContainer />
            <main className="pt-20 overflow-y-hidden">
              {children}
            </main>
          </ClientProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
